# Generated by Django 4.1 on 2022-08-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total',
        ),
    ]
