# Generated by Django 3.2.5 on 2022-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
